# Generated by Django 6.0.3 on 2026-04-11 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchenorder',
            old_name='Food_name',
            new_name='food_name',
        ),
    ]
