# Generated by Django 6.0.3 on 2026-04-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_food_name_kitchenorder_food_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Served', 'Served')], default='Pending', max_length=20),
        ),
    ]
